#!/usr/bin/env node

/**
 * Rollback — Restore pre-workflow state
 *
 * Usage:
 *   node scripts/rollback.js [--workflow-id <id>] [--force]
 *
 * Options:
 *   --workflow-id <id>  Rollback a specific workflow (default: latest)
 *   --force             Skip interactive confirmation (audit log still fires)
 */

'use strict';

const { execFileSync } = require('node:child_process');
const { readFileSync, writeFileSync, existsSync, unlinkSync, mkdirSync } = require('node:fs');
const { join, resolve, sep } = require('node:path');
const readline = require('node:readline');

const PROJECT_ROOT = join(__dirname, '..');
const AGENT_DIR = join(PROJECT_ROOT, '.agent-assistant');
const SNAPSHOT_FILE = join(AGENT_DIR, 'rollback-snapshot.json');
const LOG_FILE = join(AGENT_DIR, 'rollback-log.json');
const CHECKPOINTS_DIR = join(AGENT_DIR, 'checkpoints');

// --- Argument parsing ---

function parseArgs(argv) {
  const args = { force: false, workflowId: null };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--force') args.force = true;
    if (argv[i] === '--workflow-id' && argv[i + 1]) args.workflowId = argv[i + 1];
  }
  return args;
}

// --- Path safety ---

/**
 * Validate that a path resolves within PROJECT_ROOT.
 * Prevents path traversal attacks via malicious snapshot data.
 */
function isPathSafe(relativePath) {
  const fullPath = resolve(PROJECT_ROOT, relativePath);
  return fullPath.startsWith(PROJECT_ROOT + sep) || fullPath === PROJECT_ROOT;
}

// --- Git detection ---

function isGitRepo() {
  try {
    execFileSync('git', ['rev-parse', '--is-inside-work-tree'], { cwd: PROJECT_ROOT, stdio: 'pipe' });
    return true;
  } catch {
    return false;
  }
}

// --- Snapshot loading ---

function loadSnapshot(workflowId) {
  if (!existsSync(SNAPSHOT_FILE)) return null;

  try {
    const data = JSON.parse(readFileSync(SNAPSHOT_FILE, 'utf8'));
    if (workflowId) {
      return data.snapshots ? data.snapshots.find(s => s.workflow_id === workflowId) : null;
    }
    // Return latest
    if (data.snapshots && data.snapshots.length > 0) {
      return data.snapshots[data.snapshots.length - 1];
    }
    return data;
  } catch (err) {
    console.error(`Error reading snapshot: ${err.message}`);
    return null;
  }
}

// --- Confirmation prompt ---

function confirm(message) {
  return new Promise((resolve) => {
    const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
    rl.question(`${message} [y/N] `, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() === 'y');
    });
  });
}

// --- Rollback log ---

function writeRollbackLog(entry) {
  if (!existsSync(AGENT_DIR)) mkdirSync(AGENT_DIR, { recursive: true });

  let log = { entries: [] };
  if (existsSync(LOG_FILE)) {
    try {
      log = JSON.parse(readFileSync(LOG_FILE, 'utf8'));
    } catch {
      log = { entries: [] };
    }
  }

  log.entries.push(entry);
  writeFileSync(LOG_FILE, JSON.stringify(log, null, 2));
  console.log(`📝 Rollback log written to ${LOG_FILE}`);
}

// --- Git rollback ---

function rollbackGit(snapshot) {
  const filesRestored = [];
  const filesDeleted = [];
  const conflicts = [];

  try {
    // Restore tracked files
    console.log('🔄 Restoring tracked files...');
    execFileSync('git', ['checkout', '--', '.'], { cwd: PROJECT_ROOT, stdio: 'pipe' });
    filesRestored.push('(all tracked files)');

    // Remove untracked files generated by workflow
    if (snapshot.generated_files && Array.isArray(snapshot.generated_files)) {
      for (const f of snapshot.generated_files) {
        if (!isPathSafe(f)) {
          console.warn(`  ⚠️  Skipping suspicious path outside project root: ${f}`);
          continue;
        }
        const fullPath = resolve(PROJECT_ROOT, f);
        if (existsSync(fullPath)) {
          unlinkSync(fullPath);
          filesDeleted.push(f);
          console.log(`  🗑️  Deleted: ${f}`);
        }
      }
    }

    // Apply stash if available
    if (snapshot.stash_message) {
      console.log('🔄 Applying stashed changes...');
      try {
        const stashList = execFileSync('git', ['stash', 'list'], { cwd: PROJECT_ROOT, encoding: 'utf8' });
        const lines = stashList.split('\n');
        const match = lines.findIndex(line => line.includes(snapshot.stash_message));

        if (match >= 0) {
          try {
            execFileSync('git', ['stash', 'apply', `stash@{${match}}`], { cwd: PROJECT_ROOT, stdio: 'pipe' });
            console.log('  ✅ Stash applied successfully');
          } catch (applyErr) {
            console.warn('  ⚠️  Stash apply had conflicts — manual resolution needed');
            conflicts.push('Stash apply conflicts detected');
          }
        } else {
          console.warn(`  ⚠️  Stash "${snapshot.stash_message}" not found — may have been dropped`);
        }
      } catch {
        console.warn('  ⚠️  Could not list stashes');
      }
    }

    return { status: conflicts.length > 0 ? 'partial' : 'success', filesRestored, filesDeleted, conflicts };
  } catch (err) {
    console.error(`❌ Git rollback failed: ${err.message}`);
    return { status: 'failed', filesRestored, filesDeleted, conflicts: [err.message] };
  }
}

// --- Non-git rollback ---

function rollbackNonGit(snapshot) {
  console.warn('⚠️  Non-git rollback is best-effort. Some changes may not be fully reversible.');
  const filesDeleted = [];

  if (snapshot.generated_files && Array.isArray(snapshot.generated_files)) {
    for (const f of snapshot.generated_files) {
      if (!isPathSafe(f)) {
        console.warn(`  ⚠️  Skipping suspicious path outside project root: ${f}`);
        continue;
      }
      const fullPath = resolve(PROJECT_ROOT, f);
      if (existsSync(fullPath)) {
        unlinkSync(fullPath);
        filesDeleted.push(f);
        console.log(`  🗑️  Deleted: ${f}`);
      }
    }
  }

  if (snapshot.modified_files && Array.isArray(snapshot.modified_files)) {
    console.warn('  ⚠️  Modified files cannot be auto-restored without git:');
    for (const f of snapshot.modified_files) {
      console.warn(`       - ${f}`);
    }
  }

  return { status: 'partial', filesRestored: [], filesDeleted, conflicts: [] };
}

// --- Stale snapshot cleanup ---

function cleanupStaleSnapshots() {
  if (!existsSync(SNAPSHOT_FILE)) return;

  try {
    const data = JSON.parse(readFileSync(SNAPSHOT_FILE, 'utf8'));
    if (!data.snapshots || !Array.isArray(data.snapshots)) return;

    const now = Date.now();
    const stale = data.snapshots.filter(s => {
      const age = now - new Date(s.timestamp).getTime();
      return age > 24 * 60 * 60 * 1000; // >24h
    });

    if (stale.length > 0) {
      console.log(`\n🧹 Found ${stale.length} stale snapshot(s) (>24h):`);
      for (const s of stale) {
        console.log(`   - ${s.workflow_id || 'unknown'} (${s.timestamp})`);
      }
      // In non-interactive mode, just report; actual cleanup requires confirmation
      console.log('   Run with interactive mode to clean up stale snapshots.');
    }
  } catch {
    // Ignore parse errors during cleanup
  }
}

// --- Main ---

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const gitMode = isGitRepo();

  console.log('🔙 Agent Assistant — Rollback');
  console.log(`   Mode: ${gitMode ? 'git' : 'non-git'}`);

  // Load snapshot
  const snapshot = loadSnapshot(args.workflowId);
  if (!snapshot) {
    console.error('❌ No rollback snapshot found.');
    console.error('   Rollback requires a pre-workflow snapshot in .agent-assistant/rollback-snapshot.json');
    process.exit(1);
  }

  console.log(`   Workflow: ${snapshot.workflow_id || 'latest'}`);
  console.log(`   Snapshot: ${snapshot.timestamp || 'unknown'}`);

  // Confirmation
  if (!args.force) {
    const confirmed = await confirm(`\n⚠️  Rollback will undo all changes from workflow "${snapshot.workflow_id || 'latest'}". Continue?`);
    if (!confirmed) {
      console.log('❌ Rollback cancelled.');
      process.exit(0);
    }
  }

  // Execute rollback
  let result;
  if (gitMode) {
    result = rollbackGit(snapshot);
  } else {
    result = rollbackNonGit(snapshot);
  }

  // Write audit log (always fires, even with --force)
  writeRollbackLog({
    timestamp: new Date().toISOString(),
    workflow_id: snapshot.workflow_id || 'unknown',
    mode: gitMode ? 'git' : 'non-git',
    files_restored: result.filesRestored,
    files_deleted: result.filesDeleted,
    conflicts: result.conflicts,
    status: result.status
  });

  // Report
  if (result.status === 'success') {
    console.log('\n✅ Rollback completed successfully.');
  } else if (result.status === 'partial') {
    console.log('\n⚠️  Rollback completed with warnings. Check log for details.');
  } else {
    console.error('\n❌ Rollback failed. Check log for details.');
    process.exit(1);
  }

  // Cleanup stale snapshots
  cleanupStaleSnapshots();
}

main().catch(err => {
  console.error(`Fatal error: ${err.message}`);
  process.exit(2);
});
